export {
    faBitbucket
} from '@fortawesome/free-brands-svg-icons';

export {
    faAngleLeft,
    faAngleRight,
    faArrowDown,
    faArrowDownToLine,
    faArrowTrendDown,
    faArrowTrendUp,
    faArrowUp,
    faArrowUpArrowDown,
    faCalendar,
    faCircle,
    faCircleArrowDown,
    faCircleArrowRight,
    faCircleArrowUp,
    faCircleCheck,
    faCircleExclamation,
    faCircleInfo,
    faCirclePlus,
    faClone,
    faCloud,
    faCopy,
    faEllipsisH,
    faFilter,
    faGear,
    faKey,
    faLock,
    faMinus,
    faPaste,
    faPlus,
    faQuestion,
    faScissors,
    faSparkles,
    faStar,
    faTrash,
    faUser,
    faXmark
} from '@fortawesome/pro-regular-svg-icons';
