export {
    faBitbucket
} from '@fortawesome/free-brands-svg-icons';

export {
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faArrowDown,
    faArrowDownToLine,
    faArrowRightLong,
    faArrowTrendDown,
    faArrowTrendUp,
    faArrowUp,
    faArrowUpArrowDown,
    faBars,
    faCalendar,
    faCalendarRange,
    faCheck,
    faCircle,
    faCircleArrowDown,
    faCircleArrowRight,
    faCircleArrowUp,
    faCircleCheck,
    faCircleExclamation,
    faCircleInfo,
    faCirclePlus,
    faClone,
    faCloud,
    faCopy,
    faEllipsisH,
    faFilter,
    faFolder,
    faGear,
    faGrid3,
    faGripDots,
    faKey,
    faLocationDot,
    faLock,
    faMinus,
    faMoon,
    faObjectsColumn,
    faPaste,
    faPlus,
    faPowerOff,
    faQuestion,
    faScissors,
    faSparkles,
    faStar,
    faSunAlt,
    faTrash,
    faUser,
    faXmark
} from '@fortawesome/pro-regular-svg-icons';
