image: node:20

clone:
  depth: 1

options:
  size: 2x

definitions:
  caches:
    dist: packages/*/dist
    modules: packages/*/node_modules
    sonar: ~/.sonar

  services:
    docker:
      memory: 4096

  steps:
    - step: &build
        name: Build
        runs-on:
          - 'self.hosted'
          - 'linux'
        caches:
          - dist
          - modules
          - node
        script:
          - npm i -g pnpm
          - pnpm install
          - pnpm build

    - step: &publish
        name: Publish
        runs-on:
          - 'self.hosted'
          - 'linux'
        caches:
          - dist
          - modules
          - node
        deployment: production
        trigger: automatic
        script:
          - npm i -g pnpm
          - pnpm install
          - pnpm build
          - pnpm run publish

    - step: &sonar-scan-main
        name: SonarQube scan
        runs-on:
          - 'self.hosted'
          - 'linux'
        caches:
          - docker
          - sonar
        services:
          - docker
        script:
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: ${SONARQUBE_HOST}
              SONAR_TOKEN: ${SONAR_TOKEN}

    - step: &sonar-scan-pr
        name: SonarQube scan
        runs-on:
          - 'self.hosted'
          - 'linux'
        caches:
          - docker
          - sonar
        services:
          - docker
        script:
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: ${SONARQUBE_HOST}
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: -Dsonar.pullrequest.key=${BITBUCKET_PR_ID}
                -Dsonar.pullrequest.branch=${BITBUCKET_BRANCH}
                -Dsonar.pullrequest.base=${BITBUCKET_PR_DESTINATION_BRANCH}

pipelines:
  branches:
    main:
      - parallel:
          - step: *sonar-scan-main
          - step: *publish

  pull-requests:
    '**':
      - parallel:
          - step: *build
          - step: *sonar-scan-pr
