packages:
    - packages/*

catalog:
    "@fortawesome/fontawesome-common-types": ^6.6.0
    "@fortawesome/free-brands-svg-icons": ^6.6.0
    "@fortawesome/pro-regular-svg-icons": ^6.6.0
    "@types/lodash-es": ^4.17.12
    "@types/luxon": ^3.4.2
    "@types/node": ^22.5.4
    "@vitejs/plugin-vue": ^5.1.3
    "@vue/language-server": ^2.1.6
    clsx: ^2.1.1
    css-class-generator: ^2.0.0
    highlight.js: ^11.10.0
    imask: ^7.6.1
    lodash-es: ^4.17.21
    luxon: ^3.5.0
    sass-embedded: ^1.78.0
    tsc-alias: ^1.8.10
    typescript: ^5.5.4
    vite: ^5.4.3
    vite-css-modules: ^1.4.2
    vue: ^3.5.3
    vue-highlight-code: ^0.2.0
    vue-router: ^4.4.3
    vue-tsc: ^2.1.6
