catalog:
  '@vitejs/plugin-vue': ^5.1.2
  '@vue/compiler-sfc': ^3.4.38
  'luxon': ^3.5.0
  'sass-embedded': ^1.77.8
  'typescript': ^5.5.4
  'vite': ^5.4.2
  'vue': ^3.4.38
  'vue-tsc': ^2.0.29

packages:
    - 'packages/*'
