export {
    faAngleLeft,
    faAngleRight,
    faArrowDownToLine,
    faCheck,
    faCircleArrowUp,
    faCircleCheck,
    faCircleExclamation,
    faCircleInfo,
    faCircleMinus,
    faCirclePlus,
    faCircleSort,
    faCircleXmark,
    faCloud,
    faEllipsisH,
    faFilter,
    faGear,
    faLock,
    faMagnifyingGlass,
    faMinus,
    faPlus,
    faRocket,
    faUser,
    faXmark
} from '@fortawesome/pro-regular-svg-icons';
