import {clsx} from 'clsx';
import {useEffect, useRef, useState} from 'react';
import type {HTMLAttributes, KeyboardEvent} from 'react';
import {FluxPrimaryButton, FluxSecondaryButton} from './Actions';
import {FluxPaneBody} from './Display';
import {useFluxDisabled} from './DisplayExtended';
import {FluxFormField, FluxFormInput} from './Forms';
import {FluxIcon} from './Icon';
import {FluxFlyout} from './Overlays';
import colorStyles from '../../../components/src/css/component/Color.module.scss';

type Triple = [number, number, number];
export type FluxColorPickerType = 'hex' | 'rgb' | 'hsl' | 'hsv';

function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value));}
function normalizeHex(value:string){const match=value.trim().match(/^#?([\da-f]{3,4}|[\da-f]{6}|[\da-f]{8})$/i);if(!match)return null;let hex=match[1];if(hex.length<=4)hex=hex.split('').map(char=>char+char).join('');return `#${hex.toLowerCase()}`;}
function hexToRgb(value:string):Triple{const hex=normalizeHex(value)?.slice(1,7)??'3b82f6';return [0,2,4].map(index=>parseInt(hex.slice(index,index+2),16)) as Triple;}
function rgbToHex([r,g,b]:Triple){return `#${[r,g,b].map(value=>clamp(Math.round(value),0,255).toString(16).padStart(2,'0')).join('')}`;}
function rgbToHsv([r,g,b]:Triple):Triple{r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min;let h=0;if(delta)h=max===r?((g-b)/delta)%6:max===g?(b-r)/delta+2:(r-g)/delta+4;h=(h/6+1)%1;return[h, max===0?0:delta/max,max];}
function hsvToRgb([h,s,v]:Triple):Triple{const i=Math.floor(h*6),f=h*6-i,p=v*(1-s),q=v*(1-f*s),t=v*(1-(1-f)*s);const values:[[number,number,number],[number,number,number],[number,number,number],[number,number,number],[number,number,number],[number,number,number]]=[[v,t,p],[q,v,p],[p,v,t],[p,q,v],[t,p,v],[v,p,q]];return values[i%6].map(value=>Math.round(value*255)) as Triple;}
function rgbToHsl(rgb:Triple):Triple{const [h,s,v]=rgbToHsv(rgb),l=v*(1-s/2),sl=l===0||l===1?0:(v-l)/Math.min(l,1-l);return[h*360,sl*100,l*100];}
function hslToRgb([degrees,percentS,percentL]:Triple):Triple{const h=((degrees%360)+360)%360/360,s=clamp(percentS/100,0,1),l=clamp(percentL/100,0,1),v=l+s*Math.min(l,1-l),sv=v===0?0:2*(1-l/v);return hsvToRgb([h,sv,v]);}

export interface FluxColorPickerProps extends Omit<HTMLAttributes<HTMLDivElement>,'defaultValue'|'onChange'> {alpha?:number;defaultAlpha?:number;defaultValue?:string|Triple;isAlphaEnabled?:boolean;onAlphaChange?:(value:number)=>void;onValueChange?:(value:string|Triple)=>void;type?:FluxColorPickerType;value?:string|Triple}
export function FluxColorPicker({alpha, className, defaultAlpha=1, defaultValue='#3b82f6', isAlphaEnabled, onAlphaChange, onValueChange, type='hex', value, ...props}:FluxColorPickerProps){const valueControlled=value!==undefined,alphaControlled=alpha!==undefined,[inner,setInner]=useState<string|Triple>(defaultValue),[innerAlpha,setInnerAlpha]=useState(defaultAlpha),current=valueControlled?value:inner,currentAlpha=alphaControlled?alpha:innerAlpha;const rgb:Triple=type==='hex'?hexToRgb(String(current)):type==='rgb'?current as Triple:type==='hsl'?hslToRgb(current as Triple):hsvToRgb(current as Triple);const hex=rgbToHex(rgb),displayHex=hex+(isAlphaEnabled?Math.round(currentAlpha*255).toString(16).padStart(2,'0'):''),[hexDraft,setHexDraft]=useState(displayHex);useEffect(()=>setHexDraft(displayHex),[displayHex]);const emitRgb=(next:Triple)=>{let output:string|Triple=rgbToHex(next);if(type==='rgb')output=next;else if(type==='hsl')output=rgbToHsl(next);else if(type==='hsv')output=rgbToHsv(next);if(!valueControlled)setInner(output);onValueChange?.(output);};const setAlpha=(next:number)=>{next=clamp(next,0,1);if(!alphaControlled)setInnerAlpha(next);onAlphaChange?.(next);};return <div {...props} className={clsx(colorStyles.colorPicker,className)}><input className={colorStyles.colorPickerSaturation} aria-label="Color" type="color" value={hex} onChange={event=>emitRgb(hexToRgb(event.currentTarget.value))}/>{isAlphaEnabled&&<input className={colorStyles.colorPickerAlphaSlider} aria-label="Opacity" type="range" min={0} max={1} step={.001} value={currentAlpha} onChange={event=>setAlpha(event.currentTarget.valueAsNumber)}/>}<div className={colorStyles.colorPickerValue}><div className={colorStyles.colorPickerPreview} style={{'--color':`rgb(${rgb.join(' ')} / ${currentAlpha})`} as React.CSSProperties} aria-hidden="true"/>{type==='hex'?<FluxFormField label="Hex"><FluxFormInput value={hexDraft} onBlur={()=>setHexDraft(displayHex)} onChange={event=>{const draft=event.currentTarget.value;setHexDraft(draft);const normalized=normalizeHex(draft);if(normalized){emitRgb(hexToRgb(normalized));if(isAlphaEnabled&&normalized.length===9)setAlpha(parseInt(normalized.slice(7),16)/255);}}}/></FluxFormField>:(['rgb','hsl','hsv'] as const).map(()=>null)}{type!=='hex'&&((type==='rgb'?rgb:type==='hsl'?rgbToHsl(rgb):rgbToHsv(rgb)) as Triple).map((part,index)=><FluxFormField key={index} label={(type==='rgb'?['R','G','B']:type==='hsl'?['H','S','L']:['H','S','V'])[index]}><FluxFormInput type="number" value={part} onChange={event=>{const values:[number,number,number]=[...(type==='rgb'?rgb:type==='hsl'?rgbToHsl(rgb):rgbToHsv(rgb))] as Triple;values[index]=event.currentTarget.valueAsNumber;emitRgb(type==='rgb'?values:type==='hsl'?hslToRgb(values):hsvToRgb(values));}}/></FluxFormField>)}</div></div>;}

const defaultColors=['#ef4444','#f97316','#f59e0b','#eab308','#84cc16','#22c55e','#10b981','#14b8a6','#06b6d4','#0ea5e9','#3b82f6','#6366f1','#8b5cf6','#a855f7','#d946ef','#ec4899','#f43f5e'];
export function FluxColorSelect({className,colors=defaultColors,defaultValue='#000000',disabled,isCustomAllowed,onValueChange,value,...props}:Omit<HTMLAttributes<HTMLDivElement>,'defaultValue'|'onChange'>&{colors?:string[];defaultValue?:string;disabled?:boolean;isCustomAllowed?:boolean;onValueChange?:(value:string)=>void;value?:string}){const controlled=value!==undefined,[inner,setInner]=useState(defaultValue),current=controlled?value:inner,[custom,setCustom]=useState(current),refs=useRef<Array<HTMLButtonElement|null>>([]),scopedDisabled=useFluxDisabled(disabled);const select=(next:string)=>{if(scopedDisabled)return;if(!controlled)setInner(next);onValueChange?.(next);};const move=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{let next:number|undefined;if(['ArrowRight','ArrowDown'].includes(event.key))next=(index+1)%colors.length;else if(['ArrowLeft','ArrowUp'].includes(event.key))next=(index-1+colors.length)%colors.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=colors.length-1;if(next!==undefined){event.preventDefault();refs.current[next]?.focus();}};return <div {...props} className={clsx(colorStyles.colorSelect,className)} role="radiogroup">{colors.map((color,index)=><button key={color} ref={element=>{refs.current[index]=element;}} className={current===color?colorStyles.colorSelectColorSelected:colorStyles.colorSelectColorDeselected} style={{'--color':color} as React.CSSProperties} type="button" role="radio" aria-checked={current===color} aria-label={color} disabled={scopedDisabled} tabIndex={scopedDisabled||(!colors.includes(current)&&index!==0)||(colors.includes(current)&&current!==color)?-1:0} onClick={()=>select(color)} onKeyDown={event=>move(event,index)}><FluxIcon className={colorStyles.colorSelectCheck} name="check" size={14}/></button>)}{isCustomAllowed&&<FluxFlyout label="Custom color" opener={({toggle})=><button className={colorStyles.colorSelectCustom} type="button" disabled={scopedDisabled} aria-label="Custom color" onClick={toggle}><FluxIcon name="ellipsis-h" size={16}/></button>}>{({close})=><><FluxColorPicker className={colorStyles.colorSelectCustomPicker} value={custom} onValueChange={value=>setCustom(String(value))}/><FluxPaneBody className={colorStyles.colorSelectButtons}><FluxSecondaryButton label="Cancel" onClick={close}/><FluxPrimaryButton label="OK" onClick={()=>{select(custom);close();}}/></FluxPaneBody></>}</FluxFlyout>}</div>;}
