import {clsx} from 'clsx';
import {Children, cloneElement, createContext, isValidElement, useContext, useId, useState} from 'react';
import type {ButtonHTMLAttributes, HTMLAttributes, KeyboardEvent, ReactElement, ReactNode} from 'react';
import type {FluxIconName, FluxPressableType, FluxTo} from '../types';
import {FluxPressable} from './Actions';
import {FluxSpinner} from './Feedback';
import {FluxIcon} from './Icon';
import {FluxFlyout} from './Overlays';
import menuStyles from '../../../components/src/css/component/Menu.module.scss';
import flyoutStyles from '../../../components/src/css/component/MenuFlyout.module.scss';
import formStyles from '../../../components/src/css/component/Form.module.scss';

const MenuContext = createContext<{close?: () => void; persistent: boolean}>({persistent: false});
export function FluxMenu({children, className, isLarge, isPersistent, onKeyDown, ...props}: HTMLAttributes<HTMLElement> & {isLarge?: boolean; isPersistent?: boolean}) { return <MenuContext.Provider value={{persistent: Boolean(isPersistent)}}><nav {...props} className={clsx(isLarge ? menuStyles.menuLarge : menuStyles.menuNormal, className)} role="menu" aria-orientation="vertical" onKeyDown={event => {onKeyDown?.(event); if (!event.defaultPrevented) menuKeys(event);}}>{children}</nav></MenuContext.Provider>; }

export interface FluxMenuItemProps extends Omit<React.ComponentProps<typeof FluxPressable>, 'children' | 'componentType'> {after?: ReactNode; before?: ReactNode; command?: string; commandIcon?: FluxIconName; commandLoading?: boolean; iconLeading?: FluxIconName; iconTrailing?: FluxIconName; imageAlt?: string; imageSrc?: string; isActive?: boolean; isDestructive?: boolean; isHighlighted?: boolean; isIndented?: boolean; isLoading?: boolean; isPersistent?: boolean; isSelectable?: boolean; isSelected?: boolean; label?: ReactNode; type?: FluxPressableType;}
export function FluxMenuItem({after, before, className, command, commandIcon, commandLoading, iconLeading, iconTrailing, imageAlt, imageSrc, isActive, isDestructive, isHighlighted, isIndented, isLoading, isPersistent, isSelectable, isSelected, label, onClick, role, type = 'button', ...props}: FluxMenuItemProps) { const menu = useContext(MenuContext); return <FluxPressable {...props} className={clsx(menuStyles.menuItem, isActive && menuStyles.menuItemActive, isDestructive && menuStyles.menuItemDestructive, isHighlighted && menuStyles.menuItemHighlighted, isIndented && menuStyles.menuItemIndented, isSelectable && isSelected && menuStyles.menuItemSelected, className)} componentType={type} role={role ?? (isSelectable ? 'menuitemradio' : 'menuitem')} aria-checked={isSelectable ? isSelected : undefined} onClick={event => {onClick?.(event); if (!event.defaultPrevented && !isPersistent && !menu.persistent) menu.close?.();}}>{isLoading ? <FluxSpinner className={menuStyles.menuItemIcon} /> : isSelectable && (!iconLeading || isSelected) ? <FluxIcon className={menuStyles.menuItemSelectableIcon} name={isSelected ? 'circle-check' : undefined} /> : imageSrc ? <img className={menuStyles.menuItemImage} src={imageSrc} alt={imageAlt ?? ''} /> : before ?? (iconLeading && <FluxIcon className={menuStyles.menuItemIcon} name={iconLeading} />)}{label && <span className={menuStyles.menuItemLabel}>{label}</span>}{iconTrailing && <FluxIcon className={menuStyles.menuItemIcon} name={iconTrailing} />}{commandLoading ? <FluxSpinner className={menuStyles.menuItemCommandIcon} size={16} /> : <>{command && <kbd className={menuStyles.menuItemCommand}>{command}</kbd>}{commandIcon && <FluxIcon className={menuStyles.menuItemCommandIcon} name={commandIcon} />}</>}{after}</FluxPressable>; }

export function FluxMenuGroup({isHorizontal, ...props}: HTMLAttributes<HTMLDivElement> & {isHorizontal?: boolean}) { return <div {...props} className={clsx(isHorizontal ? menuStyles.menuGroupHorizontal : menuStyles.menuGroupVertical, props.className)} role="group" />; }
export function FluxMenuPane(props: HTMLAttributes<HTMLDivElement>) { return <div {...props} className={clsx(menuStyles.menuPane, props.className)} data-flux-menu-pane="" role="group" />; }
export function FluxMenuTitle({title, ...props}: HTMLAttributes<HTMLDivElement> & {title: ReactNode}) { return <div {...props} className={clsx(menuStyles.menuTitle, props.className)} role="presentation">{title}</div>; }
export function FluxMenuSubHeader({iconLeading, iconTrailing, label, ...props}: HTMLAttributes<HTMLDivElement> & {iconLeading?: FluxIconName; iconTrailing?: FluxIconName; label: ReactNode}) { return <div {...props} className={clsx(menuStyles.menuSubHeader, props.className)} role="presentation">{iconLeading && <FluxIcon className={menuStyles.menuSubHeaderIcon} name={iconLeading} />}<span className={menuStyles.menuSubHeaderLabel}>{label}</span>{iconTrailing && <FluxIcon className={menuStyles.menuSubHeaderIcon} name={iconTrailing} />}</div>; }
export function FluxMenuControl({children, disabled, iconLeading, isFill, label, ...props}: HTMLAttributes<HTMLDivElement> & {disabled?: boolean; iconLeading?: FluxIconName; isFill?: boolean; label?: ReactNode}) { const id = useId(); return <div {...props} className={clsx(menuStyles.menuControl, disabled && menuStyles.menuControlDisabled, isFill && menuStyles.menuControlFill, props.className)} role="group" aria-labelledby={label ? id : undefined}>{iconLeading && <FluxIcon className={menuStyles.menuControlIcon} name={iconLeading} />}{label && <span id={id} className={menuStyles.menuControlLabel}>{label}</span>}<div className={menuStyles.menuControlContent}>{children}</div></div>; }

export function FluxMenuCheckbox({checked, onCheckedChange, ...props}: Omit<FluxMenuItemProps, 'isSelectable' | 'isSelected'> & {checked: boolean; onCheckedChange(checked: boolean): void}) { return <FluxMenuItem {...props} isPersistent isSelectable isSelected={checked} role="menuitemcheckbox" onClick={event => {props.onClick?.(event); if (!event.defaultPrevented) onCheckedChange(!checked);}} />; }
export function FluxMenuToggle({checked, onCheckedChange, ...props}: Omit<FluxMenuItemProps, 'after'> & {checked: boolean; onCheckedChange(checked: boolean): void}) { return <FluxMenuItem {...props} isPersistent role="menuitemcheckbox" aria-checked={checked} after={<span className={clsx(formStyles.formToggle, checked && formStyles.isChecked)} aria-hidden="true"><span className={formStyles.formToggleInput} /></span>} onClick={event => {props.onClick?.(event); if (!event.defaultPrevented) onCheckedChange(!checked);}} />; }

export function FluxMenuOptions({children, isHorizontal, mode = 'highlight', onValueChange, value}: {children: ReactNode; isHorizontal?: boolean; mode?: 'highlight' | 'select'; onValueChange(value: string | number): void; value: string | number}) { return <FluxMenuGroup isHorizontal={isHorizontal}>{Children.map(children, (child, index) => {if (!isValidElement(child)) return child; const item = child as ReactElement<FluxMenuItemProps>, identity = typeof child.key === 'string' || typeof child.key === 'number' ? child.key : index; return cloneElement(item, {isHighlighted: mode === 'highlight' && value === identity, isPersistent: true, isSelectable: mode === 'select', isSelected: mode === 'select' && value === identity, onClick: event => {item.props.onClick?.(event); if (!event.defaultPrevented) onValueChange(identity);}});})}</FluxMenuGroup>; }

export function FluxMenuCollapsible({children, defaultOpened, disabled, iconLeading, label}: {children: ReactNode; defaultOpened?: boolean; disabled?: boolean; iconLeading?: FluxIconName; label?: ReactNode}) { const [open, setOpen] = useState(Boolean(defaultOpened)); const id = useId(); return <div className={open ? menuStyles.menuCollapsibleOpened : menuStyles.menuCollapsible}><FluxMenuItem disabled={disabled} iconLeading={iconLeading} iconTrailing={open ? 'angle-down' : 'angle-right'} isPersistent label={label} aria-expanded={open} aria-controls={id} onClick={() => setOpen(value => !value)} />{open && <div id={id} className={menuStyles.menuCollapsibleBody} role="group"><div className={menuStyles.menuCollapsibleContent}>{children}</div></div>}</div>; }
export function FluxMenuFlyout({children, disabled, icon, label}: {children: ReactNode; disabled?: boolean; icon?: FluxIconName; label?: ReactNode}) { return <FluxFlyout direction="horizontal" opener={({isOpen, toggle}) => <FluxMenuItem className={isOpen ? flyoutStyles.menuFlyoutTriggerOpen : undefined} disabled={disabled} iconLeading={icon} iconTrailing="angle-right" isPersistent label={label} aria-haspopup="menu" aria-expanded={isOpen} onClick={toggle} />}>{({close}) => <MenuContext.Provider value={{close, persistent: false}}><div className={flyoutStyles.menuFlyoutPopup} role="menu">{children}</div></MenuContext.Provider>}</FluxFlyout>; }

function menuKeys(event: KeyboardEvent<HTMLElement>) { if (!['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key)) return; const items = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('[role^=menuitem]:not([aria-disabled=true])')); if (!items.length) return; const current = items.indexOf(document.activeElement as HTMLElement); const next = event.key === 'Home' ? 0 : event.key === 'End' ? items.length - 1 : (current + (event.key === 'ArrowUp' ? -1 : 1) + items.length) % items.length; items[next]?.focus(); event.preventDefault(); }
