name: Pre-release Flux

on:
    release:
        types: [ prereleased ]

env:
    RELEASE_VERSION: ${{ github.event.release.tag_name }}

permissions:
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        name: 🚀 Publish to Registry
        steps:
            -   name: 👀 Checkout
                uses: actions/checkout@v4

            -   name: ⚙️ Setup Bun
                uses: oven-sh/setup-bun@v2

            -   name: 📦️ Install dependencies
                run: bun install --frozen-lockfile
                env:
                    FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

            -   name: ✏️ Tag v${{ env.RELEASE_VERSION }}
                run: |
                    bun pm version --cwd packages/types ${{ env.RELEASE_VERSION }}
                    bun pm version --cwd packages/internals ${{ env.RELEASE_VERSION }}
                    bun pm version --cwd packages/components ${{ env.RELEASE_VERSION }}
                    bun pm version --cwd packages/dashboard ${{ env.RELEASE_VERSION }}
                    
                    sed -i 's/workspace:\*/${{ env.RELEASE_VERSION }}/g' packages/types/package.json
                    sed -i 's/workspace:\*/${{ env.RELEASE_VERSION }}/g' packages/internals/package.json
                    sed -i 's/workspace:\*/${{ env.RELEASE_VERSION }}/g' packages/components/package.json
                    sed -i 's/workspace:\*/${{ env.RELEASE_VERSION }}/g' packages/dashboard/package.json

            -   name: 🔨 Build v${{ env.RELEASE_VERSION }}
                run: |
                    bun --cwd packages/internals build
                    bun --cwd packages/components build
                    bun --cwd packages/dashboard build
                    bun --cwd docs build
                env:
                    FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

            -   name: 🚀 Publish v${{ env.RELEASE_VERSION }}
                run: |
                    bun publish --cwd packages/types --access public --tag next
                    bun publish --cwd packages/internals --access public --tag next
                    bun publish --cwd packages/components --access public --tag next
                    bun publish --cwd packages/dashboard --access public --tag next
                env:
                    FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
                    NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: 🚀 Publish Docs
                uses: cloudflare/pages-action@v1
                id: publish
                with:
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    accountId: 5e565cf9fa55b0eae1f8131903da2ca9
                    branch: ${{ github.head_ref || github.ref_name }}
                    projectName: fluxui
                    directory: docs/.vitepress/dist
                    gitHubToken: ${{ secrets.GITHUB_TOKEN }}

            -   name: ⭐️ Output
                run: |
                    echo "Build ID: ${{ steps.publish.outputs.id }}"
                    echo "Publish URL: ${{ steps.publish.outputs.url }}"
                    echo "Environment: ${{ steps.publish.outputs.environment }}"
                    echo "Alias: ${{ steps.publish.outputs.alias }}"
